# Site settings
title: Fishing
description: > # this means to ignore newlines until "baseurl:"
    Sam's Fishing Blog
url: "http://fishing.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
